theme: jekyll-theme-minimal
title: Welcome!
description: This is where you can learn more about my career and interests.
![Headshot](https://github.com/d2rd/glenn-david/blob/gh-pages/DD-Bizhead_234x234.jpg "Glenn-David Daniel")
